sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ahsan722505/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ahsan722505/docker-react npm run test